### ISSUE TITLE
 from .cv2 import * 遇到 ImportError

### ISSUE THREAD

**Issue by skhe** [TheNetAdmin/JJGamer#1]
```
(env) λ python Gamer.py
Traceback (most recent call last):
  File "Gamer.py", line 2, in <module>
    from Utils.Elements import Chess, PlayGround
  File "C:\Users\skhe\JJGamer\Utils\Elements.py", line 1, in <module>
    import cv2 as cv
  File "C:\Users\skhe\wechat_jump_game\env\lib\site-packages\cv2\__init__.py", line 9, in <module>
    from .cv2 import *
ImportError: DLL load failed: 找不到指定的模块。

(env) λ pip freeze | grep opencv
opencv-python==3.3.0.10
```

对opencv-python版本有要求？

**Comment by TheNetAdmin** [comment]
```
C:\Users\PrinceXuan
λ pip freeze | grep opencv
opencv-python==3.4.0.12
```
我的是这个版本，不知道3.3是否可用

**Comment by skhe** [comment]
多谢。我试一下。

**Comment by TheNetAdmin** [comment]
现在已经可以使用了么，如果可以的话我就关掉这个issue了。
